name: Auto Merge frontend and backend to main

on:
  push:
    branches:
      - frontend
      - backend

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Merge frontend
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git pull origin main
          git merge origin/frontend --no-edit || true
          git push origin main

      - name: Merge backend
        run: |
          git merge origin/backend --no-edit || true
          git push origin main
